query LanceFlowProject($login: String!, $number: Int!) {
  user(login: $login) {
    projectV2(number: $number) {
      id
      title
      fields(first: 30) {
        nodes {
          ... on ProjectV2SingleSelectField {
            id
            name
            options {
              id
              name
            }
          }
        }
      }
      items(first: 100) {
        nodes {
          id
          fieldValues(first: 12) {
            nodes {
              ... on ProjectV2ItemFieldSingleSelectValue {
                name
                field {
                  ... on ProjectV2SingleSelectField {
                    name
                  }
                }
                optionId
              }
            }
          }
          content {
            ... on Issue {
              number
              title
            }
            ... on DraftIssue {
              title
            }
          }
        }
      }
    }
  }
}
